Repository Pankaj0038/dcodeKi, pull requests merged in 2024-02, with the labels that each got.

#81 Add Gray code encoding and decoding functionalities
  dcodeKi-app/dcodeKi.kv
  dcodeKi-app/dcodeKi.py
  dcodeKi-app/encoders/gray.py
Labels: easy, JWOC

#83 Using API to get Contributors info
  Components/contributers/contributor.js
  Components/contributors/contributor.js
  Components/contributors/contributors.css
  Components/contributors/contributors.html
  index.html
Labels: hard, JWOC

#86 Solving redundancy
  dcodeKi-app/dcodeKi.py
Labels: medium, JWOC

#90 Added Customized Scrollbar
  Components/conatact_page/contact.css
  Components/contributors/contributors.css
  Components/downloads/download.css
  style.css
Labels: medium, JWOC
